function validate_construct()
% Known-groups construct validation for the Prompt Quality Agent (paper
% Section 4.7). No human raters required.
%
% Logic: IFEval prompts are constraint-rich and well-specified BY DESIGN
% (known-high group). Each is paired with a degraded variant generated by
% deleting most content words and shuffling the remainder, destroying
% specificity, completeness, and structure BY CONSTRUCTION (known-low
% group). If the Prompt Quality Agent measures the intended construct, it
% must score the known-high group above its paired known-low variant.
%
% Output: results/construct_validation.mat plus one printed summary block.
% Paste the entire printed output back into the chat.

    rng(42, 'twister');
    api = Ollama_API('qwen2.5:7b');

    data = jsondecode(fileread('data/master_benchmark.json'));
    is_ife = strcmp(string(data.source), "ifeval");
    ife_prompts = data.prompts(is_ife);

    n_target = 100;
    idx = randperm(numel(ife_prompts));
    idx = idx(1:min(n_target, numel(ife_prompts)));

    n = numel(idx);
    hi = nan(n, 4); % specificity, completeness, ambiguity, structure
    lo = nan(n, 4);

    fprintf('Known-groups validation: %d prompt pairs...\n', n);
    for i = 1:n
        p_high = ife_prompts{idx(i)};
        p_low  = degrade_prompt(p_high);

        try
            q = PromptQualityAgent(p_high, api);
            hi(i,:) = [q.specificity, q.completeness, q.ambiguity, q.structure];
        catch err
            fprintf('Pair %d high-group error (%s). Skipping.\n', i, err.message);
        end
        try
            q = PromptQualityAgent(p_low, api);
            lo(i,:) = [q.specificity, q.completeness, q.ambiguity, q.structure];
        catch err
            fprintf('Pair %d low-group error (%s). Skipping.\n', i, err.message);
        end
        fprintf('Pair %d/%d done\n', i, n);
    end

    hi_mean = mean(hi, 2, 'omitnan'); % per-prompt composite (mean of 4 dims)
    lo_mean = mean(lo, 2, 'omitnan');

    save('results/construct_validation.mat', 'hi', 'lo', 'hi_mean', 'lo_mean');

    ok = ~isnan(hi_mean) & ~isnan(lo_mean);
    h = hi_mean(ok); l = lo_mean(ok);

    fprintf('\n===== CONSTRUCT VALIDATION (known groups) =====\n');
    fprintf('Valid pairs: %d\n', sum(ok));
    fprintf('Known-high (IFEval originals): mean %.3f, median %.3f\n', mean(h), median(h));
    fprintf('Known-low (degraded variants): mean %.3f, median %.3f\n', mean(l), median(l));
    fprintf('Discrimination rate (high > low): %.3f\n', mean(h > l));
    report_wilcoxon('Composite: high vs low', h, l);

    dims = {'Specificity', 'Completeness', 'Ambiguity', 'Structure'};
    for d = 1:4
        okd = ~isnan(hi(:,d)) & ~isnan(lo(:,d));
        fprintf('%s: high mean %.2f vs low mean %.2f\n', ...
            dims{d}, mean(hi(okd,d)), mean(lo(okd,d)));
    end
    fprintf('===== END =====\n');
end

function degraded = degrade_prompt(prompt)
% Destroys prompt quality by construction: randomly deletes 60 percent of
% words, then shuffles the survivors. The result is underspecified,
% incomplete, and unstructured relative to its source, providing a
% known-low quality group without any human labeling.
    words = strsplit(strtrim(prompt));
    nw = numel(words);
    keep = max(3, round(nw * 0.4));
    sel = randperm(nw, keep);
    words = words(sort(sel));       % random deletion
    words = words(randperm(keep));  % order shuffle
    degraded = strjoin(words, ' ');
end

function report_wilcoxon(label, a, b)
% Paired Wilcoxon signed-rank, normal approximation, base MATLAB only.
    d = a - b;
    d = d(d ~= 0);
    n = numel(d);
    if n < 10
        fprintf('%s: insufficient pairs (n=%d)\n', label, n);
        return;
    end
    [~, sidx] = sort(abs(d));
    ranks = zeros(n,1);
    sa = abs(d(sidx));
    i = 1;
    while i <= n
        j = i;
        while j < n && sa(j+1) == sa(i)
            j = j + 1;
        end
        ranks(sidx(i:j)) = (i + j) / 2;
        i = j + 1;
    end
    Wp = sum(ranks(d > 0));
    Wm = sum(ranks(d < 0));
    mu = n*(n+1)/4;
    sd = sqrt(n*(n+1)*(2*n+1)/24);
    z = (min(Wp,Wm) - mu) / sd;
    p = erfc(abs(z)/sqrt(2));
    rb = (Wp - Wm) / (Wp + Wm);
    fprintf('%s: n=%d, z=%.2f, p=%.4g, rank-biserial r=%.3f\n', label, n, z, p, rb);
end
